name: Update Taskboard

on:
  push:
    branches:
      - main
  issues:
    types: [opened, edited, closed]
  issue_comment:
    types: [created]

jobs:
  update-taskboard:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Update tasks.json
      id: update_json
      run: |
        cat <<EOT > tasks.json
        {
          "tasks": [
            {
              "title": "Task 1",
              "description": "Description for Task 1",
              "status": "red"
            }
          ]
        }
        EOT

    - name: Commit and push changes
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'
        git add tasks.json
        git commit -m 'Update taskboard'
        git push https://x-access-token:${GH_TOKEN}@github.com/${{ github.repository }}.git

    - name: Send notification to Discord
      env:
        DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
      run: |
        TASK=$(jq -r '.tasks[-1]' tasks.json)
        TITLE=$(echo $TASK | jq -r '.title')
        DESCRIPTION=$(echo $TASK | jq -r '.description')
        STATUS=$(echo $TASK | jq -r '.status')
        COLOR="0"
        case $STATUS in
          "green") COLOR="65280" ;; # Green
          "red") COLOR="16711680" ;; # Red
          "orange") COLOR="16753920" ;; # Orange
          "yellow") COLOR="16776960" ;; # Yellow
          "lightblue") COLOR="65535" ;; # Light Blue
        esac
        curl -H "Content-Type: application/json" \
        -d '{
            "embeds": [
              {
                "title": "'"$TITLE"'",
                "description": "'"$DESCRIPTION"'",
                "color": '"$COLOR"'
              }
            ]
          }' \
        $DISCORD_WEBHOOK_URL
